language: ruby
rvm:
- 2.6.5
addons:
  postgresql: 9.6
env:
  global:
  - CC_TEST_REPORTER_ID=146d8f2d057309414efe547598ed9fbdc20c94c3e1195c1028cad6e363f4cbfb
  - secure: DB9Gve0P/VwRh+bCvHEbdoEK2epPNQBf1Pb4dwU+vjZQlpJZWSjBnY/Xq+vPQu/bUPQLjiuWaISG1eCfcPc9IHIDz3pIzUssU5mpIsCFb7s1Z3gM+2TnUPfTvR9LJ9JXZ8yCh6NKe/IM2TIZFC7fANCWI55dG40qtDrCFQN0z79nUO4pYj/rGY4P89/ANrds5p97z30SToyg/QGIT4sPoQIPWFFHvlUuRbBpfg04eB6itT1m2uSdW6bgaOQrnaW7SbEXo/VD2jHckXcKu5nkChesUZTUeHtdV8+8uF/1PvZTwUq9pZNZieRWfLSrx76hNWBq9OfQD7o9n2Vhonp3SjbXVu8DJOuhLoW2mYD7fGDjvLl2NQ1QuayeNw9WvgBMuskMEmdlRxO8HYrbbu7SJR2YcJ4NL8VYLR0K70/ak2MkKHjeLwDaIOLnoEs1hYQkdzQLU/AZJiZLO+/bxlganr4lgiDZkgDPTbdJ2sZWb862LIo0ecpSlsFPtZcY9oezUfcJxOJsZn7C13EJ6ZjV+MM9q4RHWahU8EQZhSkbD9IrtwC3hJBAcjjz95/NgKQpiLlW+Zup76ok73lUAOAFhr968W36FFw+PVLgvDLQmkKd66hCJHSeWmBYRhoBWTwU39sXK4dYeSseC9nUjiU6QWLrsSjw8mpxjbo/ZOLFZz8=
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
